<a href="https://colab.research.google.com/github/Nidhi89717/tensorflow/blob/main/01_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.11.0'

In [2]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scaler.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10.,7],
                             [3.,5],
                             [6.,4]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  5.],
       [ 6.,  4.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[10,7,4],
                       [1,4,7]],
                      [[2,6,9],
                       [4,7,3]],
                      [[1,6,9],
                      [8,5,2]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  7,  4],
        [ 1,  4,  7]],

       [[ 2,  6,  9],
        [ 4,  7,  3]],

       [[ 1,  6,  9],
        [ 8,  5,  2]]], dtype=int32)>

In [11]:
tensor.ndim

3

###Creating Tensors with tf.Variable

In [12]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
unchangeable_tensor[0].assign(8)
unchangeable_tensor

AttributeError: ignored

In [16]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [17]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [5,8]])

not_shuffled,tf.random.shuffle(not_shuffled)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 5,  8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [ 5,  8],
        [10,  7]], dtype=int32)>)

https://www.tensorflow.org/api_docs/python/tf/random/set_seed

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A
randomly picked seed is used for this op.<br>

2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.<br>

3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.<br>

4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [18]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  8]], dtype=int32)>

In [19]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  8]], dtype=int32)>

### Other ways to make tensors

In [20]:
#create tensors of all ones
tf.ones([4,3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [21]:
# Create tensors of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

We can convert numpy arrays into tensors<br>

Remember, the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

>Note: A matrix or tensor is typically represented by a capital letter (e.g. X or A) where as a vector is typically represented by a lowercase letter (e.g. y or b).

In [22]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [24]:
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [25]:
A.ndim

3

##Getting information from tensors (shape, rank, size)


**Shape**: The length (number of elements) of each of the dimensions of a tensor.<br>
**Rank**: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.<br>
**Axis** or **Dimension**: A particular dimension of a tensor.<br>
**Size**: The total number of items in the tensor.

In [26]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor) 

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
print(f"Datatype of every element: {rank_4_tensor.dtype}")
print(f"Number of dimensions (rank): {rank_4_tensor.ndim}")
print(f"Shape of tensor: {rank_4_tensor.shape}")
print(f"Elements along the zero axis: {rank_4_tensor.shape[0]}")
print(f"Elements along the last axis: {rank_4_tensor.shape[-1]}")
print(f"Total number of elements in tensor: {tf.size(rank_4_tensor)}")

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the zero axis: 2
Elements along the last axis: 5
Total number of elements in tensor: 120


### Indexing tensors

In [30]:
#Get the first two elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
#Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
#Create a rank 2 tensor
rank_2_tensor = tf.constant([[3,7],
                             [4,10]])

In [33]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [34]:
# Get last item of each row of rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [35]:
#Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[ 4],
        [10]]], dtype=int32)>

In [36]:
# Alternate to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[ 4],
        [10]]], dtype=int32)>

In [37]:
tf.expand_dims(rank_2_tensor,axis=0) # Expand the zero axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 3,  7],
        [ 4, 10]]], dtype=int32)>

In [38]:
tf.expand_dims(rank_2_tensor,axis=1) #Expand the middle (axis=1) axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[ 3,  7]],

       [[ 4, 10]]], dtype=int32)>

### Manipulating Tensors (tensor operations)

In [39]:
tensor = tf.constant([[10,3],[4,7]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [14, 17]], dtype=int32)>

In [40]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 4,  7]], dtype=int32)>

In [41]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 40,  70]], dtype=int32)>

In [42]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -7],
       [-6, -3]], dtype=int32)>

In [43]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 40,  70]], dtype=int32)>

### Matrix Multiplication

In [44]:
#Matrix multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[112,  51],
       [ 68,  61]], dtype=int32)>

In [45]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[112,  51],
       [ 68,  61]], dtype=int32)>

In [47]:
x = tf.constant([[3,5],
                 [6,7],
                 [1,8]])

y = tf.constant([[1,2],
                 [3,4],
                 [6,7]])

In [48]:
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [6, 7]], dtype=int32)>)

In [49]:
#x @ y

In [50]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 36, 44],
       [34, 54, 67],
       [33, 50, 59]], dtype=int32)>

In [51]:
tf.matmul(x, tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 36, 44],
       [34, 54, 67],
       [33, 50, 59]], dtype=int32)>

In [52]:
tf.matmul(tf.reshape(y,shape=(2,3)),x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 18,  43],
       [ 55, 118]], dtype=int32)>

In [53]:
tf.matmul(tf.transpose(y),x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 74],
       [37, 94]], dtype=int32)>

**The dot product**

The matrix multiplication is also referred to as the dot product

One can perform the matrix multiplication using:
* 'tf.matmul()'
* 'tf.tensordot()'
* '@'

In [54]:
tf.tensordot(tf.transpose(y),x,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 74],
       [37, 94]], dtype=int32)>

In [55]:
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 29, 53],
       [20, 46, 85],
       [17, 35, 62]], dtype=int32)>

In [56]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 36, 44],
       [34, 54, 67],
       [33, 50, 59]], dtype=int32)>

In [57]:
print('Normal y')
print(y,'\n')

print('Y reshaped to (2,3):')
print(tf.reshape(y,shape=(2,3)),'\n')

print('y transposed:')
print(tf.transpose(y))

Normal y
tf.Tensor(
[[1 2]
 [3 4]
 [6 7]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[1 2 3]
 [4 6 7]], shape=(2, 3), dtype=int32) 

y transposed:
tf.Tensor(
[[1 3 6]
 [2 4 7]], shape=(2, 3), dtype=int32)


But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, we will transpose (not reshape) one of them in order to line them up.

### Changing the datatype of a tensor

In [58]:
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [59]:
C = tf.constant([2,3])
C.dtype

tf.int32

In [60]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B,dtype=tf.float16)
D.dtype

tf.float16

In [61]:
E = tf.cast(C,dtype=tf.int16)
E.dtype

tf.int16

### Aggregating Tensors

Aggregating tensors = Condensing them from multiple values down to smaller amount of values 

In [62]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [63]:
# Get the absolue value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Forms of aggregation

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [64]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([85, 47, 20, 46, 62, 18, 43, 82, 44, 97,  1,  3, 84, 32, 49, 56, 57,
       77, 37, 52, 19, 58, 43, 41, 91, 71, 40, 40, 57, 79,  7, 47, 17, 36,
       54, 44, 24, 96, 22,  9, 45, 11, 46, 19, 96, 43,  8, 72, 47, 79])>

In [65]:
tf.size(E), E.ndim, E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [66]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [67]:
# Find the maximun
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [68]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [69]:
# Find the sum of a tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2353>

In [70]:
# Find the variance of a tensor
#tf.reduce_variance(E)  # won't work

In [71]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=677>

In [72]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=677.7364>

In [73]:
# Find the Standard Deviation of a tensor
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.033371>

In [74]:
#tf.math.reduce_std(E)

### Find the positional maximum and minimum

In [75]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [76]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [77]:
# Index of largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [78]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [79]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [80]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [81]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [82]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [83]:
G.squeezed = tf.squeeze(G)
G.squeezed, G.squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [84]:
# Create a list of indicies
some_list = [0,1,2,3] # could be red, blue, green, purple

# One hot encode some_list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [85]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value='yo I love deep learning', off_value='I also love to dance')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also love to dance',
        b'I also love to dance', b'I also love to dance'],
       [b'I also love to dance', b'yo I love deep learning',
        b'I also love to dance', b'I also love to dance'],
       [b'I also love to dance', b'I also love to dance',
        b'yo I love deep learning', b'I also love to dance'],
       [b'I also love to dance', b'I also love to dance',
        b'I also love to dance', b'yo I love deep learning']],
      dtype=object)>

### Squaring, log, Square root

In [86]:
H = tf.range(10)
H 

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [87]:
# Square it
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [88]:
# Find the square root (method requires non-int type )
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [89]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [90]:
# Find the reciprocal
tf.math.reciprocal(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([       inf, 0.99999994, 0.49999997, 0.3333333 , 0.24999999,
       0.19999999, 0.16666666, 0.14285713, 0.125     , 0.11111111],
      dtype=float32)>

In [91]:
# Find the power
tf.math.pow(tf.cast(H,dtype=tf.float32),2.0)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)>

### Manipulating `tf.Variable` tensors

Tensors created with `tf.Variable()` can be changed in place using methods such as:

* [`.assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) - assign a different value to a particular index of a variable tensor.
* [`.add_assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) - add to an existing value and reassign it at a particular index of a variable tensor.


In [92]:
# Create a variable tensor
I = tf.Variable(np.arange(0,5))
I 

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [93]:
# Assign the final value a new value of 50
I.assign([1,2,3,4,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 1,  2,  3,  4, 50])>

In [94]:
# The change happens in place (the last value is now 50, not 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 1,  2,  3,  4, 50])>

In [95]:
# Add 10 to every element in I
I.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([11, 12, 13, 14, 60])>

In [96]:
# Again, the change happens in place
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([11, 12, 13, 14, 60])>

### Tensors and Numpy

TensorFlow interacts beautifully with NumPy arrays.

In [97]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [98]:
# Convert tensor back to NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [99]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [100]:
# The default types of each are slighty different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [101]:
#tf.config.list_physical_devices()

In [102]:
#!nvidia-smi

**Note**: If you have access to a GPU, TensorFlow will automatically use it whenever possible.

###TensorFlow Fundamentals Exercises

In [103]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
scalar = tf.constant(10)
vector = tf.constant([10,20])
matrix = tf.constant([[1,2],
                      [3,4]])
tensor = tf.constant([[[1,2,3],
                       [4,3,2]],
                      [[5,6,8],
                       [10,2,13]]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  3,  2]],
 
        [[ 5,  6,  8],
         [10,  2, 13]]], dtype=int32)>)

In [104]:
# 2. Find the shape, rank and size of the tensors you created in 1. 
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 2, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [105]:
# 3.Create two tensors containing random values between 0 and 1 with shape [5, 300].
random_tensor1 = tf.random.uniform(shape=(5,300))
random_tensor2 = tf.random.uniform(shape=(5,300))

random_tensor1, random_tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
         0.2584542 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936

In [106]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication
random_tensor1 @ tf.transpose(random_tensor2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.714005, 80.87824 , 78.32848 , 78.259705, 79.130585],
       [70.12708 , 72.09945 , 70.1678  , 73.24609 , 74.277405],
       [75.16    , 79.52858 , 76.74644 , 78.14265 , 77.28679 ],
       [77.113556, 75.401215, 72.79378 , 75.066376, 75.206535],
       [79.87284 , 83.40138 , 78.57373 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [107]:
# 5. Multiply the two tensors you created in 3 using dot product.
tf.tensordot(random_tensor1,tf.transpose(random_tensor2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.714005, 80.87824 , 78.32848 , 78.259705, 79.130585],
       [70.12708 , 72.09945 , 70.1678  , 73.24609 , 74.277405],
       [75.16    , 79.52858 , 76.74644 , 78.14265 , 77.28679 ],
       [77.113556, 75.401215, 72.79378 , 75.066376, 75.206535],
       [79.87284 , 83.40138 , 78.57373 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [108]:
#6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
random_tensor3 = tf.random.uniform(shape=(224,224,3))
random_tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [109]:
#7.Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_min(random_tensor3[0]), tf.reduce_max(random_tensor3[1])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0006545782>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99712765>)

In [110]:
#8.Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor2 = tf.constant(np.random.rand(1,224,224,3))
tensor2.shape,tf.squeeze(tensor2), tf.squeeze(tensor2).shape

(TensorShape([1, 224, 224, 3]),
 <tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
 array([[[0.92590579, 0.89389909, 0.62266992],
         [0.5504471 , 0.37605228, 0.49310963],
         [0.81937792, 0.69426472, 0.80346079],
         ...,
         [0.88836644, 0.74088214, 0.50556972],
         [0.24911024, 0.32940787, 0.62361231],
         [0.47194852, 0.3669231 , 0.52274714]],
 
        [[0.95822481, 0.50129583, 0.64188198],
         [0.97701794, 0.92742445, 0.68004269],
         [0.13007787, 0.27588472, 0.91426178],
         ...,
         [0.60512858, 0.9640033 , 0.41843655],
         [0.89295899, 0.69181313, 0.24019622],
         [0.56019744, 0.21040796, 0.54801053]],
 
        [[0.02546991, 0.80933887, 0.39794252],
         [0.59625247, 0.56988932, 0.79082573],
         [0.54893878, 0.92570016, 0.24617845],
         ...,
         [0.89619339, 0.00777437, 0.23792708],
         [0.65185592, 0.78125432, 0.42649456],
         [0.6107445 , 0.26569465, 0.59006637]],
 
        ...,
 


In [111]:
#9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor3 = np.arange(10)
tensor3, tf.argmax(tensor3)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 <tf.Tensor: shape=(), dtype=int64, numpy=9>)

In [112]:
#10.One-hot encode the tensor you created in 9.
tf.one_hot(tensor3, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>